// <auto-generated />
using System;
using Alura.ListaLeitura.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Alura.WebAPI.DAL.Livros.Migrations
{
    [DbContext(typeof(LeituraContext))]
    partial class LeituraContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Alura.ListaLeitura.Modelos.Livro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Autor")
                        .HasColumnType("nvarchar(75)");

                    b.Property<byte[]>("ImagemCapa")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Lista")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Resumo")
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Subtitulo")
                        .HasColumnType("nvarchar(75)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Livros");
                });
#pragma warning restore 612, 618
        }
    }
}
